import Head from 'next/head'
import { Nav } from './src/components/nav'
import { Hero } from './src/components/hero'
import { Faq } from './src/components/info_section'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav></Nav>
      <Hero></Hero>
      <Faq></Faq>
    </div>
  )
}
