import Head from 'next/head'
import { Nav } from '../components/nav'
import { Hero } from '../components/hero'
import { Faq } from '../components/info_section'
import { Contact } from '../components/contact'
import { Footer } from '../components/footer'
import { Feature } from '../components/feature'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Nav></Nav>
      <Hero></Hero>
      <Feature></Feature>
      <Faq></Faq>
      <Contact></Contact>
      <Footer></Footer>
    </div>
  )
}
